
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router-dom";


import { UserGuard } from "app";


import { StackHandlerRoutes, LoginRedirect } from "app/auth";


const About = lazy(() => import("./pages/About.tsx"));
const Activity = lazy(() => import("./pages/Activity.tsx"));
const ActivityFeed = lazy(() => import("./pages/ActivityFeed.tsx"));
const App = lazy(() => import("./pages/App.tsx"));
const CreateHousehold = lazy(() => import("./pages/CreateHousehold.tsx"));
const Demo = lazy(() => import("./pages/Demo.tsx"));
const Features = lazy(() => import("./pages/Features.tsx"));
const Household = lazy(() => import("./pages/Household.tsx"));
const JoinHousehold = lazy(() => import("./pages/JoinHousehold.tsx"));
const LandingPage = lazy(() => import("./pages/LandingPage.tsx"));
const Pantry = lazy(() => import("./pages/Pantry.tsx"));
const Pricing = lazy(() => import("./pages/Pricing.tsx"));
const Root = lazy(() => import("./pages/Root.tsx"));
const ShoppingListDetail = lazy(() => import("./pages/ShoppingListDetail.tsx"));
const ShoppingLists = lazy(() => import("./pages/ShoppingLists.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/auth/redirect", element: <LoginRedirect />},
	{ path: "/auth/*", element: <StackHandlerRoutes />},
	{ path: "/about", element: <UserGuard><About /></UserGuard>},
	{ path: "/activity", element: <UserGuard><Activity /></UserGuard>},
	{ path: "/activity-feed", element: <UserGuard><ActivityFeed /></UserGuard>},
	{ path: "/activityfeed", element: <UserGuard><ActivityFeed /></UserGuard>},
	{ path: "/", element: <App />},
	{ path: "/create-household", element: <UserGuard><CreateHousehold /></UserGuard>},
	{ path: "/createhousehold", element: <UserGuard><CreateHousehold /></UserGuard>},
	{ path: "/demo", element: <UserGuard><Demo /></UserGuard>},
	{ path: "/features", element: <UserGuard><Features /></UserGuard>},
	{ path: "/household", element: <UserGuard><Household /></UserGuard>},
	{ path: "/join-household", element: <UserGuard><JoinHousehold /></UserGuard>},
	{ path: "/joinhousehold", element: <UserGuard><JoinHousehold /></UserGuard>},
	{ path: "/landing-page", element: <UserGuard><LandingPage /></UserGuard>},
	{ path: "/landingpage", element: <UserGuard><LandingPage /></UserGuard>},
	{ path: "/pantry", element: <UserGuard><Pantry /></UserGuard>},
	{ path: "/pricing", element: <UserGuard><Pricing /></UserGuard>},
	{ path: "/root", element: <UserGuard><Root /></UserGuard>},
	{ path: "/shopping-list-detail", element: <UserGuard><ShoppingListDetail /></UserGuard>},
	{ path: "/shoppinglistdetail", element: <UserGuard><ShoppingListDetail /></UserGuard>},
	{ path: "/shopping-lists", element: <UserGuard><ShoppingLists /></UserGuard>},
	{ path: "/shoppinglists", element: <UserGuard><ShoppingLists /></UserGuard>},

];
